---

- hosts: all
  become: true
  tasks:

  - name: install apache2 and php package on Debian
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_os_family == "Debian"

  - name: install httpd and php package on RedHat
    dnf:
      name:
        - httpd
        - php
      state: present
      update_cache: yes
    when: ansible_os_family == "RedHat"

  - name: Start apache service on Red Hat
    systemd:
      name: httpd
      state: started
      enabled: true
    when: ansible_os_family == "RedHat"
