---

- hosts: all
  become: true
  tasks:

  - name: install updates (RedHat)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "RedHat"

  - name: install updates (Debian)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Debian"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache  and php for RedHat servers
    tags: apache,centos,httpd
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "RedHat"

  - name: Start apache service on RedHat
    systemd:
      name: httpd
      state: started
      enabled: true
    when: ansible_os_family == "RedHat"

- hosts: db_servers
  become: true
  tasks:

  - name: install apache2 and php for Debian servers
    tags: mariadb,apache2,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_os_family == "Debian"
  
  - name: install mariadb package (Ubuntu)
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

  - name: install apache2 and php for Debian servers
    tags: samba,file_servers
    apt:
      name:
        - apache2
        - samba
      state: latest
    when: ansible_os_family == "Debian"  

#  - name: Install samba package on "Ubuntu"
#   apt:
#      name: smbd
#      state: latest
#    when: ansible_distribution == "Ubuntu"
  
  - name: start and enable samba == "Ubuntu"
    tags: samba
    service:
      name: smbd
      state: started
      enabled: true
    when: ansible_os_family == "Debian"
