---

- hosts: all
  become: true
  tasks:

  - name: Start apache2 package on Ubuntu/Debian
    systemd:
      name: apache2
      state: started
      enabled: true
    when: ansible_distribution == "Ubuntu"

  - name: Start apache service on Red Hat
    systemd:
      name: httpd
      state: started
      enabled: true
    when: ansible_distribution in ["RedHat", "Centos"]
