- name: add ssh key for cooter
  authorized_key: 
    user: cooter
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJVH2KSmiqytL9+jvjJnbtsKPXTKwLsZjXqLx/dVSZ/O ansible"

- name: generate sshd_config file friom template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd
