- name: install unzip
  package:
    name: unzip

- name: install terraform
  unarchive:
    src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes
    mode: 0755
    owner: root
    group: root

- name: install httpd package on RedHat/Centos
  dnf:
    name: httpd
    state: present
    update_cache: yes
  when: ansible_os_family == "RedHat"

- name: Start apache service on Red Hat
  systemd:
    name: httpd
    state: started
    enabled: true
  when: ansible_distribution in ["RedHat", "Centos"]
